CPPFLAGS = -Wall -std=c++14

FOLDER = ../../_posts/
FILE = 0005-01-01-topic2.md

all: clean solver fin fall
	./solver < fin.txt > fout.txt
	diff fall.txt fout.txt

clean:
	rm -rf solver *.txt

fin:
	@ cat $(FOLDER)$(FILE) | sed -n '/\__begin__/,/\<\TagEnd/p' | sed '/^\s*$$/d; /^\#/d; /^ /d' > fin.txt
	cat fin.txt
fall:
	@ cat $(FOLDER)$(FILE) | sed -n '/\TagBegin/,/\<\TagEnd/p' | sed '/^\s*$$/d; /^\#/d' > fall.txt

#fout:
#	@ cat $(FOLDER)$(FILE) | sed -n '/\TagBegin/,/\<\TagEnd/p' | sed '/^\s*$$/d; /^\#/d; /^[a-zA-Z0-9]/d' | sed -e 's/^[ \t]*//' > fout.txt
